version: 2
updates:
  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Project
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
