name: Analyze

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  analyze:
    name: Ubuntu
    runs-on: ubuntu-latest
    permissions:
      packages: read
      security-events: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Add GitHub Packages Source
      run: |
        dotnet nuget add source \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
